import type { Scenario } from '../types';

/**
 * Default example plan, transcribed from the spec's section 14 initial data
 * table plus the recurring items (rent/living/savings/part-time income)
 * called for in the surrounding text.
 */
export function buildSeedScenario(): Scenario {
  return {
    id: 'scenario-base',
    name: '기본 계획',
    isDefault: true,
    createdAt: new Date().toISOString(),
    settings: {
      baseCurrency: 'KRW',
      startMonth: '2026-07',
      forecastMonths: 36,
      monthlyEssentialLiving: 700_000,
      livingReserveMonths: 3,
      emergencyFund: 1_000_000,
      shortTermExpenseMonths: 3,
      investmentAllocationRate: 0.5,
    },
    assets: [
      {
        id: 'asset-checking',
        name: '입출금 통장',
        type: 'cash',
        principal: 3_000_000,
        marketValue: 3_000_000,
        liquidity: 'immediate',
        note: '초기 보유 현금',
      },
    ],
    cashFlows: [
      {
        id: 'income-army-savings',
        name: '군적금 해지',
        type: 'income',
        category: 'other_income',
        amount: 18_000_000,
        startMonth: '2026-09',
        recurrence: 'once',
      },
      {
        id: 'income-part-time',
        name: '아르바이트 수입',
        type: 'income',
        category: 'part_time',
        amount: 2_000_000,
        startMonth: '2026-10',
        recurrence: 'monthly',
        adjustable: true,
      },
      {
        id: 'expense-living',
        name: '생활비',
        type: 'expense',
        category: 'living',
        amount: 700_000,
        startMonth: '2026-07',
        recurrence: 'monthly',
        required: true,
      },
      {
        id: 'expense-rent',
        name: '월세',
        type: 'expense',
        category: 'rent',
        amount: 550_000,
        startMonth: '2026-10',
        recurrence: 'monthly',
        required: true,
      },
      {
        id: 'expense-iphone',
        name: '아이폰',
        type: 'expense',
        category: 'equipment',
        amount: 800_000,
        startMonth: '2026-07',
        recurrence: 'once',
        adjustable: true,
      },
      {
        id: 'expense-macmini',
        name: '맥미니',
        type: 'expense',
        category: 'equipment',
        amount: 890_000,
        startMonth: '2026-07',
        recurrence: 'once',
        adjustable: true,
      },
      {
        id: 'expense-gift',
        name: '선물',
        type: 'expense',
        category: 'gift',
        amount: 1_500_000,
        startMonth: '2026-09',
        recurrence: 'once',
      },
      {
        id: 'expense-settlement',
        name: '정착비',
        type: 'expense',
        category: 'other_expense',
        amount: 1_500_000,
        startMonth: '2026-10',
        recurrence: 'once',
      },
      {
        id: 'expense-monitor',
        name: '모니터',
        type: 'expense',
        category: 'equipment',
        amount: 300_000,
        startMonth: '2026-11',
        recurrence: 'once',
        adjustable: true,
      },
      {
        id: 'expense-monitor-arm',
        name: '모니터암',
        type: 'expense',
        category: 'equipment',
        amount: 50_000,
        startMonth: '2026-11',
        recurrence: 'once',
        adjustable: true,
      },
      {
        id: 'expense-thunderbolt-dock',
        name: '썬더볼트 독',
        type: 'expense',
        category: 'equipment',
        amount: 700_000,
        startMonth: '2026-11',
        recurrence: 'once',
        adjustable: true,
      },
      {
        id: 'expense-3d-printer',
        name: '3D프린터',
        type: 'expense',
        category: 'equipment',
        amount: 750_000,
        startMonth: '2026-11',
        recurrence: 'once',
        adjustable: true,
      },
      {
        id: 'expense-nas',
        name: 'NAS',
        type: 'expense',
        category: 'equipment',
        amount: 1_000_000,
        startMonth: '2027-02',
        recurrence: 'once',
        adjustable: true,
      },
    ],
    transfers: [
      {
        id: 'transfer-gov-savings',
        name: '정부지원 저축 납입',
        kind: 'saving',
        from: 'cash',
        to: 'government_savings',
        amount: 500_000,
        startMonth: '2026-08',
        recurrence: 'monthly',
      },
      {
        id: 'transfer-deposit-equity',
        name: '보증금 자기자본',
        kind: 'saving',
        from: 'cash',
        to: 'deposit',
        amount: 1_500_000,
        startMonth: '2026-10',
        recurrence: 'once',
      },
    ],
    loans: [
      {
        id: 'loan-deposit',
        name: '월세 보증금 정책대출',
        principal: 3_500_000,
        annualRate: 0.013,
        startMonth: '2026-10',
        repaymentType: 'bullet',
        termMonths: 24,
        purpose: '월세 보증금',
        proceedsTo: 'deposit',
      },
    ],
  };
}
