import type { Scenario } from '../types';

/**
 * Default example plan, transcribed from the revised spec's section 20
 * sample data table plus the recurring items (월세·관리비/생활비/아르바이트)
 * described alongside it.
 */
export function buildSeedScenario(): Scenario {
  return {
    id: 'scenario-base',
    name: '기본 계획',
    isDefault: true,
    createdAt: new Date().toISOString(),
    settings: {
      baseCurrency: 'KRW',
      startMonth: '2026-07',
      forecastMonths: 36,
      minimumCashAmount: 3_000_000,
      shortTermExpenseMonths: 3,
    },
    assets: [
      {
        id: 'asset-checking',
        name: '입출금 통장',
        type: 'cash',
        principal: 3_000_000,
        marketValue: 3_000_000,
        liquidity: 'immediate',
        includeInAvailableCash: true,
        note: '초기 보유 현금',
      },
    ],
    events: [
      {
        id: 'event-iphone',
        type: 'expense',
        name: '아이폰',
        amount: 800_000,
        month: '2026-07',
        category: 'device',
        active: true,
      },
      {
        id: 'event-macmini',
        type: 'expense',
        name: '맥미니',
        amount: 890_000,
        month: '2026-07',
        category: 'device',
        active: true,
      },
      {
        id: 'event-gov-savings',
        type: 'transfer',
        name: '정부지원 저축',
        amount: 500_000,
        month: '2026-08',
        category: 'government_savings',
        active: true,
        recurrence: { frequency: 'monthly', startMonth: '2026-08' },
        transfer: { kind: 'saving', from: 'cash', to: 'government_savings' },
      },
      {
        id: 'event-army-savings',
        type: 'income',
        name: '군적금 해지',
        amount: 18_000_000,
        month: '2026-09',
        category: 'asset_sale',
        active: true,
      },
      {
        id: 'event-gift',
        type: 'expense',
        name: '선물',
        amount: 1_500_000,
        month: '2026-09',
        category: 'gift',
        active: true,
      },
      {
        id: 'event-deposit-loan',
        type: 'loan',
        name: '월세 보증금 정책대출',
        amount: 3_500_000,
        month: '2026-10',
        active: true,
        loan: {
          annualRate: 0.013,
          repaymentType: 'bullet',
          maturityMonth: '2028-09',
          proceedsTo: 'deposit',
          purpose: '월세 보증금',
        },
      },
      {
        id: 'event-deposit-equity',
        type: 'transfer',
        name: '보증금 자기자본',
        amount: 1_500_000,
        month: '2026-10',
        category: 'other_transfer',
        active: true,
        transfer: { kind: 'saving', from: 'cash', to: 'deposit' },
      },
      {
        id: 'event-settlement',
        type: 'expense',
        name: '정착비',
        amount: 1_500_000,
        month: '2026-10',
        category: 'other_expense',
        active: true,
      },
      {
        id: 'event-part-time',
        type: 'income',
        name: '아르바이트',
        amount: 2_000_000,
        month: '2026-10',
        category: 'part_time',
        active: true,
        recurrence: { frequency: 'monthly', startMonth: '2026-10' },
      },
      {
        id: 'event-rent',
        type: 'expense',
        name: '월세·관리비',
        amount: 500_000,
        month: '2026-10',
        category: 'housing',
        active: true,
        required: true,
        recurrence: { frequency: 'monthly', startMonth: '2026-10' },
      },
      {
        id: 'event-living',
        type: 'expense',
        name: '생활비',
        amount: 500_000,
        month: '2026-10',
        category: 'living',
        active: true,
        required: true,
        recurrence: { frequency: 'monthly', startMonth: '2026-10' },
      },
      {
        id: 'event-monitor',
        type: 'expense',
        name: '모니터',
        amount: 300_000,
        month: '2026-11',
        category: 'device',
        active: true,
      },
      {
        id: 'event-monitor-arm',
        type: 'expense',
        name: '모니터암',
        amount: 50_000,
        month: '2026-11',
        category: 'device',
        active: true,
      },
      {
        id: 'event-thunderbolt-dock',
        type: 'expense',
        name: '썬더볼트 독',
        amount: 700_000,
        month: '2026-11',
        category: 'device',
        active: true,
      },
      {
        id: 'event-3d-printer',
        type: 'expense',
        name: '3D프린터',
        amount: 750_000,
        month: '2026-11',
        category: 'device',
        active: true,
      },
      {
        id: 'event-nas',
        type: 'expense',
        name: 'NAS',
        amount: 1_000_000,
        month: '2027-02',
        category: 'device',
        active: true,
      },
    ],
  };
}
